name: 'chat'
version: 0.0.1
description: Multithreaded chat.
author: Alexey Korkota <alexey.korkota@gmail.com>
homepage: https://github.com/korkota/chat

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^0.1.0'
  protobuf: '0.5.0'
  intl: '0.12.4'

dev_dependencies:
  test: '0.12.6'

executables:
  dart_coveralls: null

transformers:
- dart_to_js_script_rewriter